### ISSUE TITLE
mobile app source url does not work

### ISSUE THREAD

**Issue by Lan-Hekary** [DiaaAshraf/RGB_ledStrip_control#2]
the link in the file points to the Project URL in your Account 
no one can access the project file through this URL except you from your account 

instead , go to your project and from the projects menu click on (export the selected project .aia to my computer ) and download the (.aia) file
than upload the (.aia) file here 

so anyone can import the project to his/her account and view it or modify it ..
thanks

**Comment by DiaaAshraf** [comment]
done thank u for ur concern
